id: P5F4187BA
initial_creation_type: input
source_metadata:
  Title: Bulletin of the Research Institute of Bukkyo University
  Editor: Kazunobu Matsuda
  Publisher: The Research Institute of Bukkyo University
  Place of Publication: Japan
  Year: '1996'
  Avikalpapraveśadhāraṇī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:56:13.485020'
last_modified_at: '2022-03-08T15:56:13.485030'
